org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_license=LGPL-3.0-or-later
mod_version=1.0.0+1.20.1
mod_name=Ayame PaperDoll:JohnMuyuan Edition
mod_id=ayame_paperdoll
mod_archives_name=ayame-paperdoll-johnmuyuan-edition
mod_description=Highly configurable PaperDoll mod for MC 1.20.1. JohnMuyuan Edition; based on Ayame PaperDoll (by HappyRespawnanchor), itself a fork of Extra Player Renderer.
mod_maven_group=org.ayamemc.ayamepaperdoll
mod_mixin_config=ayame-paperdoll.mixins.json
mod_homepage_url=https://github.com/JohnMuyuan/Ayame-PaperDoll
mod_fabric_sources_url=https://github.com/JohnMuyuan/Ayame-PaperDoll
mod_issues_url=https://github.com/JohnMuyuan/Ayame-PaperDoll/issues
mod_access_widener_name=ayame-paperdoll.accesswidener

# Minecraft / dependencies
minecraft_version=1.20.1
fabric_minecraft_version_range=>=1.20.1 <1.20.2
fabric_loader_version=0.16.14
fabric_api_version=0.92.11+1.20.1
fabric_api_dependency_version=0.92.0+1.20.1
modmenu_version=7.2.2
